---
name: Prometheus
version: dev
slug: prometheus
description: Cloud native metrics
url: https://github.com/hassio-addons/addon-prometheus
codenotary: codenotary@frenck.dev
startup: services
ingress: true
ingress_port: 9090
ingress_entry: graph
init: false
panel_icon: mdi:chart-timeline
panel_title: Prometheus
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
homeassistant_api: true
map:
  - share:rw
ports:
  9090/tcp: null
ports_description:
  9090/tcp: Not required for Ingress
